logging:
  level:
    org.springframework.web : DEBUG
    org.springframework.data: ERROR

server:
  port: 9988
  servlet:
    context-path: /
    path: /animator



spring:
  data:
    mongodb:
      uri: "mongodb+srv://ankugupta:ejNU1XHWT6dVU5zb@cluster-animator-trtta.mongodb.net/animator?retryWrites=true&w=majority"
#      uri: "mongodb://ec2-13-232-69-230.ap-south-1.compute.amazonaws.com/animator"
    
